---
secret:
  - name: "Ext_Int_User"
    provider: "environment-variable"
    parameters:
      variable: "EXT_INT_USER"
      path:
  - name: "Ext_Int_Password"
    provider: "environment-variable"
    parameters:
      variable: "EXT_INT_PASSWORD"
      path:
secrets_group:
  - name: "Ext_Int_API_Credentials"
    secrets:
      - name: "Ext_Int_User"
        secret_type: "username"
        access_type: "HTTP(S)"
      - name: "Ext_Int_Password"
        secret_type: "password"
        access_type: "HTTP(S)"
tag:
  - name: "Test"
    color: "ff9800"
    description: "Test"
    content_types:
      - "extras.externalintegration"
# external_integration:
#   - name: "Test Integration"
#     remote_url: "https://my.integration.instance:45322"
#     timeout: 30
#     verify_ssl: false
#     secrets_group_name: "Ext_Int_API_Credentials"
#     headers:
#       Accept: "application/yang-data+json"
#       Content-Type: "application/yang-data+json"
#     http_method: "POST"
#     ca_file_path: "/tmp/ca.crt"
#     extra_config:
#       test_extra_config:
#         - "extra_value"
#     tags: ["Test"]
